name: pLobby
version: ${project.version}
main: br.pryz.lobby.main.LobbyMain
api-version: 1.19
author: PryzDev
description: Plugin de gerenciamento de lobby
commands:
  sair:
    description: Remove o jogador do modo pvp.
    aliases: [quit]